# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-26 12:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='bithday',
            new_name='birthday',
        ),
    ]
