# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-06-11 21:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0005_journal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journal',
            name='visiting',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=b'', verbose_name='\u0424\u043e\u0442\u043e'),
        ),
    ]
